# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 732fde3e88c3e0a03e7f1bb72a6033163f97abc5098bd498de47e7ff15209a7b07c3c96a004529edf405128fe1b1003696bb4336cf2705951022f0c60631bd5f

test:
  secret_key_base: 928aacfe7c933e4d1bbea514172d8b1cffb15bbbecd1902617c960409c266c7e644c1350e7d9f999f0f1b01c8b660dc773a057f2c5b054cfd88aed2229fa7d49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
